### PR TITLE
[MCB-0001] Connect Mindcraft agent to MC server

### PR DESCRIPTION
**Pull request by nikshepsvn**
My current progress on making the mindcraft agent connect to the server that is spun up by manager, currently fails with
```
Starting mindcraft agent...
[ './andy.json' ]
keys.json not found. Defaulting to environment variables.
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
Using embedding settings: { api: 'openai' }
(node:23259) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Logging in...
/Users/nikshepsvn/orchestrator/mindcraft/node_modules/mineflayer/lib/loader.js:108
    const version = require('minecraft-data')(bot._client.version).version
                                                                  ^

TypeError: Cannot read properties of null (reading 'version')
    at next (/Users/nikshepsvn/orchestrator/mindcraft/node_modules/mineflayer/lib/loader.js:108:67)
    at createBot (/Users/nikshepsvn/orchestrator/mindcraft/node_modules/mineflayer/lib/loader.js:105:34)
    at initBot (file:///Users/nikshepsvn/orchestrator/mindcraft/src/utils/mcdata.js:57:15)
    at Agent.start (file:///Users/nikshepsvn/orchestrator/mindcraft/src/agent/agent.js:27:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.0.0
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.
```

which from poking around seems related to the MC server version, the MC server should be running in a compatible version tho (1.20.4) so not sure what is going on, feel free to add a fix to this branch if someone can figure it out, else I'll take a deeper look soon

### CODE REVIEW

**Comment by nikshepsvn** [comment]
please set OPENAI_API_KEY in .env in the same folder for auth!

**Comment by jessedubbink** [comment]
Just dropping this here regarding your issue with mineflayer.
No clue if this works, but might point you in the right direction 😊

[Similar issue](https://github.com/PrismarineJS/mineflayer/issues/1659#issuecomment-780887598)

[Possible fix](https://github.com/PrismarineJS/mineflayer/discussions/1689)

**Comment by nikshepsvn** [comment]
> Just dropping this here regarding your issue with mineflayer. No clue if this works, but might point you in the right direction 😊
> 
> [Similar issue](https://github.com/PrismarineJS/mineflayer/issues/1659#issuecomment-780887598)
> 
> [Possible fix](https://github.com/PrismarineJS/mineflayer/discussions/1689)

seems like this is related to 'protocolVersion' so not the same, the error here is a check failing for the actual MC server version. currently we're figuring out a spec/plan on how we want to actually implement the agent/issuing build commands so I'll hold off with this PR till we have clearer direction

**Comment by nikshepsvn** [comment]
closing! we went with mineflayer instead #4

**Pull request closed without merging**
